kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
    - npm install
    - npm run test
    - npm run coverage
- name: npm
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    token: 
      from_secret: npm_token
    email:
      from_secret: npm_email