kind: pipeline
type: docker
name: default

steps:
- name: npm
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password: 
      from_secret: npm_password
    email:
      from_secret: npm_email